### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by Danubius1st** [openscript/react-router-private-protected-routes#2]
I ran your app and I got this warning:
`bundle.js:sourcemap:8738 Warning: Cannot update a component (`SessionContextProvider`) while rendering a different component (`App`). To locate the bad setState() call inside `App`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at App (http://localhost:3001/static/js/bundle.js:141:125)
    at SessionContextProvider (http://localhost:3001/static/js/bundle.js:641:90)
    at Router (http://localhost:3001/static/js/bundle.js:36104:15)
    at BrowserRouter (http://localhost:3001/static/js/bundle.js:35584:5)
`

**Comment by Danubius1st** [comment]
I just fixed the problem by moving `<SessionContextProvider>` from `index.tsx` to `App.tsx`.
